//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        public MetodoPago()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int IdMetodoPago { get; set; }
        public string Metodo { get; set; }
    
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
