//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ProductoSucursals = new HashSet<ProductoSucursal>();
            this.VentaProductoes = new HashSet<VentaProducto>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int Stock { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<ProductoSucursal> ProductoSucursals { get; set; }
        public virtual ICollection<VentaProducto> VentaProductoes { get; set; }
    }
}
